[build]

# FIXME: Once the mkdocs material PR is merged, we can remove this file
# and set this in the Netlify site settings directly.

publish = "site/"

# Default build command.
command = """
    # For social cards - not sure if these are really needed or not
    apt-get install libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev
    # Build docs
    mkdocs build
    """
